### ISSUE TITLE
Filter by namespace

### ISSUE THREAD

**Issue by FlominatorTM** [pietrodn/intersect-contribs#5]
Great tool. Except for finding common topics, I also saw people using it finding their own most popular articles by intersecting with themselves.
For both purposes it would be pretty cool, if one could filter by namespace or reduce the search to article namespace. 

Thanks in advance and happy easter, Flo

**Comment by pietrodn** [comment]
Thanks for the suggestion!
The namespace filter is not very difficult to implement, I'll do it in my
spare time (which sadly is not that much).
I'm very happy that my tool is somewhat popular. :)
Regards

Il giorno sab 26 mar 2016 alle ore 23:25 Florian Straub <
notifications@github.com> ha scritto:

> Great tool. Except for finding common topics, I also saw people using it
> finding their own most popular articles by intersecting with themselves.
> For both purposes it would be pretty cool, if one could filter by
> namespace or reduce the search to article namespace.
>
> Thanks in advance and happy easter, Flo
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pietrodn/intersect-contribs/issues/5>
>
-- 
Pietro De Nicolao

**Comment by pietrodn** [comment]
I've implemented the feature. Let me know if it's okay for you! :)

**Comment by FlominatorTM** [comment]
Thank you, that's exactly what I meant.

PS: I'm still waiting for my results (almost 100k edits), but colleague with 120 edits was good for testing :)

**Comment by FlominatorTM** [comment]
What a pity, doesn't load for me at all :(

**Comment by pietrodn** [comment]
The problem is that the tool is painfully slow for users with big contribution histories.
Currently the intersection is done by the database. I am considering whether doing it in the script instead... but I'd only do it if I'm sure that I can do better than the DB optimizer, which seems pretty hard.
